---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-v2
  labels:
    app: blog-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-v2
  template:
    metadata:
      labels:
        app: blog-v2
    spec:
      containers:
        - name: blog-v2
          image: ghcr.io/skill-wanderer/blog-v2:latest
          ports:
            - containerPort: 80
          env:
            # Firebase Configuration from Secret
            - name: PUBLIC_FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: firebase-config
                  key: FIREBASE_API_KEY
            - name: PUBLIC_FIREBASE_AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: firebase-config
                  key: FIREBASE_AUTH_DOMAIN
            - name: PUBLIC_FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: firebase-config
                  key: FIREBASE_PROJECT_ID
            - name: PUBLIC_FIREBASE_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: firebase-config
                  key: FIREBASE_STORAGE_BUCKET
            - name: PUBLIC_FIREBASE_MESSAGING_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: firebase-config
                  key: FIREBASE_MESSAGING_SENDER_ID
            - name: PUBLIC_FIREBASE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: firebase-config
                  key: FIREBASE_APP_ID
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          imagePullPolicy: Always
