# Firebase Configuration Secret
# This file contains the Firebase configuration that will be injected as environment variables
# Replace the placeholder values with your actual Firebase project configuration

apiVersion: v1
kind: Secret
metadata:
  name: firebase-config
  namespace: default
type: Opaque
stringData:
  FIREBASE_API_KEY: "your-firebase-api-key-here"
  FIREBASE_AUTH_DOMAIN: "your-project-id.firebaseapp.com"
  FIREBASE_PROJECT_ID: "your-project-id"
  FIREBASE_STORAGE_BUCKET: "your-project-id.appspot.com"
  FIREBASE_MESSAGING_SENDER_ID: "your-messaging-sender-id"
  FIREBASE_APP_ID: "your-app-id"
