name: Dependency Update

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Update dependencies
        run: |
          npm update
          npm audit fix --force || true

      - name: Test build after updates
        run: |
          npm ci
          npm run build:production

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'Automated dependency update'
          body: |
            This PR contains automated dependency updates.
            
            ## Changes
            - Updated npm dependencies to latest versions
            - Applied security fixes where available
            
            ## Testing
            - [x] Build process validated
            - [x] No breaking changes detected
          branch: automated-dependency-update
          delete-branch: true